<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DebugType>embedded</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <ApplicationIcon>icon\zip.ico</ApplicationIcon>
        <IsPackable>false</IsPackable>
        <AssemblyVersion>2.9.0</AssemblyVersion>
        <FileVersion>2.9.0</FileVersion>
        <NeutralLanguage>en</NeutralLanguage>
        <Company>PureLogicCode.com</Company>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <!-- Single-file publish settings -->
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="SimpleZipDrive.Tests" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SimpleZipDrive.Core\SimpleZipDrive.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DokanNet" Version="2.3.0.3" />
        <PackageReference Include="Meziantou.Analyzer" Version="3.0.231">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.Analyzers" Version="5.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="5.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.Formatting.Analyzers" Version="5.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="SharpCompress" Version="0.50.4" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="References\**" />
        <None Update="7z.dll">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="7z_arm64.dll">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="References\**" />
    </ItemGroup>

    <ItemGroup>
        <Page Remove="References\**" />
    </ItemGroup>
</Project>