<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <AssemblyVersion>2.8.0</AssemblyVersion>
        <FileVersion>2.8.0</FileVersion>
        <NeutralLanguage>en</NeutralLanguage>
        <Company>PureLogicCode.com</Company>
        <DebugType>embedded</DebugType>
        <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="SimpleZipDrive" />
        <InternalsVisibleTo Include="SimpleZipDrive_WinFsp" />
        <InternalsVisibleTo Include="SimpleZipDrive.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Meziantou.Analyzer" Version="3.0.200">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.Analyzers" Version="5.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="5.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Roslynator.Formatting.Analyzers" Version="5.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="SharpCompress" Version="0.50.4" />
        <PackageReference Include="SharpSevenZip" Version="2.0.115" />
    </ItemGroup>

</Project>
